# Generated by Django 4.0.5 on 2022-06-27 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='music',
            name='cover',
        ),
    ]
