# Generated by Django 4.0.5 on 2022-06-27 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_remove_music_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='staticfiles/covers/', verbose_name='Poster'),
        ),
    ]
